---
AWSTemplateFormatVersion: '2010-09-09'
Description: >
  An standalone openvpn server with a privately isolated pki certification
  authority. Code design comprises a two-level hierarchical structure composed
  of a single root and one-level of child nested templates.

  Orchestration is controlled via shell script commands and is achieved in a
  three phase stack creation/update process that is promoted via a counter
  variable.

  Nested template components include:

  A Virtual Private Cloud.
  A Network Access Control List.
  A Public and Private Security Group definition.
  A Public EC2 Instance declaration.
  A Private EC2 Instance declaration.
  An Auto Scaling Group.
  A EC2 Launch Template.
  A SNS Notification Topic.
  A Cloudwatch Alarm.
  A Target Group.
  A Network Load Balancer.
  A DNS Record Set.

# ------------------------------------------


# ==========================================
Metadata: {}
# Metadata:


# ==========================================
# Parameters {}
Parameters:

  # ------------------------------------------
  # --- The Project Name
  ProjectName:
    Description: "The Name given to this Project."
    ConstraintDescription: "Specify Project Name"
    Type: String
    Default: "cfn-bckt-www-cli"
    MinLength: 3
    MaxLength: 63
    AllowedPattern:
      (?!^(\d{1,3}\.){3}\d{1,3}$)(^[a-z0-9]([a-z0-9-]*(\.[a-z0-9])?)*$(?<!\-))

  # ------------------------------------------
  # --- The Hosted Zone Domain Name
  DomainBaseURL:
    Description: "Domain Base URL Hosted Zone Apex"
    Type: String
    Default: "cloudemprise.net"
    AllowedPattern:
      ^(([a-zA-Z]{1})|([a-zA-Z]{1}[a-zA-Z]{1})|([a-zA-Z]{1}[0-9]{1})|([0-9]{1}[a-zA-Z]{1})|([a-zA-Z0-9][a-zA-Z0-9-_]{1,61}[a-zA-Z0-9]))\.([a-zA-Z]{2,6}|[a-zA-Z0-9-]{2,30}\.[a-zA-Z]{2,3})$

  # ------------------------------------------
  # --- The Domain Hosted Zone ID
  DomainHostedZoneId:
    Description: "An Amazon Route 53 hosted zone ID"
    Type: AWS::Route53::HostedZone::Id

  # ------------------------------------------
  # --- Script Build Step Counter
  BuildStep:
    Description: "Shell script step counter"
    Type: String
    Default: "stage1"
    AllowedValues:
      - "stage1"
      - "stage2"
      - "stage3"

  # ------------------------------------------
  # --- Route 53 Hosted Zone ID
  # DomainHostedZoneId:
    # Description: "An Amazon Route 53 hosted zone ID"
    # Type: "AWS::Route53::HostedZone::Id"

  # ------------------------------------------
  # --- SNS Email Notifications
  EmailAddrSNS:
    Description: "Openvpn SNS Email Endpoint"
    ConstraintDescription: "Must be a valid email address"
    Type: String
    Default: "dh.info@posteo.net"
    AllowedPattern:
      ^([a-zA-Z0-9_\-\.]+)@([a-zA-Z0-9_\-\.]+)\.([a-zA-Z]{2,5})$


# ==========================================
Conditions: {}
# Conditions:


# ==========================================
Resources:

  # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  #         NESTED STACK DECLARATIONS
  # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  # ------------------------------------------
  # --- S3 Bucket Definitions
  BucketDefs:
    Type: "AWS::CloudFormation::Stack"
    # .............................
    Properties:
      TemplateURL:
        !Sub "https://${ProjectName}.s3.${AWS::Region}.amazonaws.com/cfn-templates/cfn-bckt-www-cli-s3.yaml"
      Parameters:
        ProjectName:
          !Ref ProjectName
        DomainBaseURL:
          !Ref DomainBaseURL
      TimeoutInMinutes: 5

  # ------------------------------------------
  # --- CDN Definition
  CloudfrontDefs:
    Type: "AWS::CloudFormation::Stack"
    # .............................
    Properties:
      TemplateURL:
        !Sub "https://${ProjectName}.s3.${AWS::Region}.amazonaws.com/cfn-templates/cfn-bckt-www-cli-cdn.yaml"
      Parameters:
        ProjectName:
          !Ref ProjectName
        DomainBaseURL:
          !Ref DomainBaseURL
        BucketWebsiteDNS:
          !GetAtt BucketDefs.Outputs.BucketWebsiteDNS
        BucketLogsDNS:
          !GetAtt BucketDefs.Outputs.BucketLogsDNS
      TimeoutInMinutes: 5

# ==========================================
Outputs: {}
# Outputs:
