---
AWSTemplateFormatVersion: '2010-09-09'
Description: >
  Add Description Here.

# ------------------------------------------


# ==========================================
Metadata: {}
# Metadata:


# ==========================================
# Parameters {}
Parameters:

  # ------------------------------------------
  # --- Name give to this project
  ProjectName:
    Description: "The Name given to this Project."
    ConstraintDescription: "Name must satisfy S3 constraints."
    Type: String
    Default: "cfn-bckt-www-cli"
    MinLength: 3
    MaxLength: 63
    AllowedPattern:
      (?!^(\d{1,3}\.){3}\d{1,3}$)(^[a-z0-9]([a-z0-9-]*(\.[a-z0-9])?)*$(?<!\-))

  # ------------------------------------------
  # --- The Base URL Domain Name
  DomainBaseURL:
    Description: "Domain Base URL Hosted Zone Apex"
    Type: String
    Default: "cloudemprise.org"
    AllowedPattern:
      ^(([a-zA-Z]{1})|([a-zA-Z]{1}[a-zA-Z]{1})|([a-zA-Z]{1}[0-9]{1})|([0-9]{1}[a-zA-Z]{1})|([a-zA-Z0-9][a-zA-Z0-9-_]{1,61}[a-zA-Z0-9]))\.([a-zA-Z]{2,6}|[a-zA-Z0-9-]{2,30}\.[a-zA-Z]{2,3})$


# ==========================================
Conditions: {}
# Conditions:


# ==========================================
Resources:


  # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  #         S3 BUCKET DEFINITION
  # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


  # ------------------------------------------
  # --- Root Bucket Definition
  BucketRootDomain:
    Type: AWS::S3::Bucket
    # .............................
    Properties:
      # .............................
      Tags:
        -
          Key: "Project"
          Value: !Sub "${ProjectName}"
      # .............................
      BucketName: !Sub "${DomainBaseURL}"
      AccessControl: PublicRead
      # .............................
      WebsiteConfiguration: 
        IndexDocument: "index.html"
        ErrorDocument: "error.html"
      # .............................
      # --- Logging performed by CDN
      #LoggingConfiguration: 
      #  DestinationBucketName: !Ref BucketLogs
      #  LogFilePrefix: "logs/"

  # ------------------------------------------
  # --- Logs Bucket Definition
  BucketLogs:
    Type: "AWS::S3::Bucket"
    # .............................
    Properties:
      # .............................
      Tags:
        -
          Key: "Project"
          Value: !Sub "${ProjectName}"
      # .............................
      BucketName: !Sub "logs.${DomainBaseURL}"
      AccessControl: LogDeliveryWrite
      # .............................
      BucketEncryption: 
        ServerSideEncryptionConfiguration: 
        - 
          ServerSideEncryptionByDefault: 
            SSEAlgorithm: "AES256"

  # ------------------------------------------
  # --- Redirect Bucket Definition
  BucketWwwRedirect:
    Type: AWS::S3::Bucket
    # .............................
    Properties:
      # .............................
      Tags:
        -
          Key: "Project"
          Value: !Sub "${ProjectName}"
      # .............................
      BucketName: !Sub "www.${DomainBaseURL}"
      AccessControl: BucketOwnerFullControl
      # .............................
      WebsiteConfiguration:
        RedirectAllRequestsTo:
          HostName: !Sub "${DomainBaseURL}"

# ==========================================
# Outputs: {}
Outputs:

  # ------------------------------------------
  # --- Website URL
  BucketRootDomainURL:
    Description: "The URL of Static Website."
    Value: !GetAtt BucketRootDomain.WebsiteURL
  # ------------------------------------------
  # --- S3 Website Bucket IPv4 DNS
  BucketRootDomainDNS:
    Description: "The IPv4 Root Bucket DNS."
    Value: !GetAtt BucketRootDomain.DomainName
  # ------------------------------------------
  # --- S3 Logs Bucket IPv4 DNS
  BucketLogsDNS:
    Description: "The IPv4 Logs Bucket DNS."
    Value: !GetAtt BucketLogs.DomainName
