---
AWSTemplateFormatVersion: '2010-09-09'
Description: >
  Configuring a S3 static website using a custom domain registered with Route 53.
  Speeding up this S3 static website with Amazon CloudFront CDN as well as
  requiring HTTPS for Communication Between Viewers and CloudFront.

  Nested template components include:

  A S3 bucket for website hosting
  A S3 bucket for website redirection.
  A S3 bucket for server logs.
  A Cloudfront content distribution network.
  A Public Certificate for TLS viewer policy.
  A DNS Record Set. 
  A SNS Notification Topic.
  A Cloudwatch Alarm.

# ------------------------------------------


# ==========================================
Metadata: {}
# Metadata:


# ==========================================
# Parameters {}
Parameters:

  # ------------------------------------------
  # --- Name give to this project
  ProjectName:
    Description: "The Name given to this Project."
    ConstraintDescription: "Name must satisfy S3 constraints."
    Type: String
    Default: "cfn-www-cicd-cli"
    MinLength: 3
    MaxLength: 63
    AllowedPattern:
      (?!^(\d{1,3}\.){3}\d{1,3}$)(^[a-z0-9]([a-z0-9-]*(\.[a-z0-9])?)*$(?<!\-))

  # ------------------------------------------
  # --- The Base URL Domain Name
  DomainBaseURL:
    Description: "Domain Base URL Hosted Zone Apex"
    Type: String
    Default: "cloudemprise.org"
    AllowedPattern:
      ^(([a-zA-Z]{1})|([a-zA-Z]{1}[a-zA-Z]{1})|([a-zA-Z]{1}[0-9]{1})|([0-9]{1}[a-zA-Z]{1})|([a-zA-Z0-9][a-zA-Z0-9-_]{1,61}[a-zA-Z0-9]))\.([a-zA-Z]{2,6}|[a-zA-Z0-9-]{2,30}\.[a-zA-Z]{2,3})$

  # ------------------------------------------
  # --- The Domain Hosted Zone ID
  DomainHostedZoneId:
    Description: "An Amazon Route 53 hosted zone ID"
    Type: AWS::Route53::HostedZone::Id

  # ------------------------------------------
  # --- ARN DomainBaseURL Certificate
  DomainCertARN:
    Description: "The ARN of the DomainBaseURL Certificate."
    Type: String

  # ------------------------------------------
  # --- Script Build Step Counter
  #BuildStep:
  #  Description: "Shell script step counter"
  #  Type: String
  #  Default: "stage1"
  #  AllowedValues:
  #    - "stage0"
  #    - "stage1"
  #    - "stage2"
  #    - "stage3"

  # ------------------------------------------
  # --- Route 53 Hosted Zone ID
  # DomainHostedZoneId:
    # Description: "An Amazon Route 53 hosted zone ID"
    # Type: "AWS::Route53::HostedZone::Id"

  # ------------------------------------------
  # --- SNS Email Notifications
  EmailAddrSNS:
    Description: "Openvpn SNS Email Endpoint"
    ConstraintDescription: "Must be a valid email address"
    Type: String
    Default: "dh.info@posteo.net"
    AllowedPattern:
      ^([a-zA-Z0-9_\-\.]+)@([a-zA-Z0-9_\-\.]+)\.([a-zA-Z]{2,5})$


# ==========================================
Conditions: {}
# Conditions:


# ==========================================
Resources:

  # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  #         NESTED STACK DECLARATIONS
  # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  # ------------------------------------------
  # --- S3 Bucket Definitions
  BucketDefs:
    Type: "AWS::CloudFormation::Stack"
    # .............................
    Properties:
      TemplateURL:
        !Sub "https://${ProjectName}.s3.${AWS::Region}.amazonaws.com/cfn-templates/cfn-www-cicd-cli-s3.yaml"
      Parameters:
        ProjectName:
          !Ref ProjectName
        DomainBaseURL:
          !Ref DomainBaseURL
      TimeoutInMinutes: 5

  # ------------------------------------------
  # --- CDN Definition
  CloudfrontDefs:
    Type: "AWS::CloudFormation::Stack"
    # .............................
    Properties:
      TemplateURL:
        !Sub "https://${ProjectName}.s3.${AWS::Region}.amazonaws.com/cfn-templates/cfn-www-cicd-cli-cdn.yaml"
      Parameters:
        ProjectName:
          !Ref ProjectName
        DomainBaseURL:
          !Ref DomainBaseURL
        BucketRootDomainDNS:
          !GetAtt BucketDefs.Outputs.BucketRootDomainDNS
        BucketLogsDNS:
          !GetAtt BucketDefs.Outputs.BucketLogsDNS
        DomainBaseURLCertificateARN:
          !Ref DomainCertARN
      TimeoutInMinutes: 5

  # ------------------------------------------
  # --- Route53 Record Set
  R53RecordSetDefs:
    Type: "AWS::CloudFormation::Stack"
    # .............................
    Properties:
      TemplateURL:
        !Sub "https://${ProjectName}.s3.${AWS::Region}.amazonaws.com/cfn-templates/cfn-www-cicd-cli-r53.yaml"
      Parameters:
        ProjectName:
          !Ref ProjectName
        DomainBaseURL:
          !Ref DomainBaseURL
        DomainHostedZoneId:
          !Ref DomainHostedZoneId
        CloudfrontURL:
          !GetAtt CloudfrontDefs.Outputs.CloudfrontURL
      TimeoutInMinutes: 5


# ==========================================
Outputs: {}
# Outputs:
