---
AWSTemplateFormatVersion: '2010-09-09'
Description: >
  Add Description Here.

# ------------------------------------------


# ==========================================
Metadata: {}
# Metadata:


# ==========================================
# Parameters {}
Parameters:

  # ------------------------------------------
  # --- The Project Name
  ProjectName:
    Description: "The Name given to this Project."
    ConstraintDescription: "Specify Project Name"
    Type: String
    Default: "cfn-bckt-www-cli"
    MinLength: 3
    MaxLength: 63
    AllowedPattern:
      (?!^(\d{1,3}\.){3}\d{1,3}$)(^[a-z0-9]([a-z0-9-]*(\.[a-z0-9])?)*$(?<!\-))

  # ------------------------------------------
  # --- The Hosted Zone Domain Name
  DomainBaseURL:
    Description: "Domain Base URL Hosted Zone Apex"
    Type: String
    Default: "cloudemprise.org"
    AllowedPattern:
      ^(([a-zA-Z]{1})|([a-zA-Z]{1}[a-zA-Z]{1})|([a-zA-Z]{1}[0-9]{1})|([0-9]{1}[a-zA-Z]{1})|([a-zA-Z0-9][a-zA-Z0-9-_]{1,61}[a-zA-Z0-9]))\.([a-zA-Z]{2,6}|[a-zA-Z0-9-]{2,30}\.[a-zA-Z]{2,3})$

  # ------------------------------------------
  # --- S3 Website Bucket IPv4 DNS
  BucketRootDomainDNS:
    Description: "The IPv4 Website Bucket DNS."
    Type: String

  # ------------------------------------------
  # --- S3 Logs Bucket IPv4 DNS
  BucketLogsDNS:
    Description: "The IPv4 Logs Bucket DNS."
    Type: String


# ==========================================
Conditions: {}
# Conditions:


# ==========================================
Resources:

  # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  #         CLOUDFRONT CDN DEFINITION
  # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


  # ------------------------------------------
  # --- Cloudfront Origin Identity Definition
  CloudFrontOriginAccessIdentity:
    Type: "AWS::CloudFront::CloudFrontOriginAccessIdentity"
    # .............................
    Properties:
      # .............................
      CloudFrontOriginAccessIdentityConfig:
        Comment: !Sub "${ProjectName}-${DomainBaseURL}-origin-identity"


  # ------------------------------------------
  # --- Cloudfront Distribution Definition
  CloudFrontDistribution:
    Type: "AWS::CloudFront::Distribution"
    # .............................
    Properties:
      # .............................
      Tags:
        -
          Key: "Name"
          Value: !Sub "${ProjectName}"
      # .............................
      DistributionConfig:
        # .............................
        Comment: "S3 Static Website CDN"
        Enabled: true
        HttpVersion: "http2"
        IPV6Enabled: false
        DefaultRootObject: "index.html"
        # .............................
        # --- Use Only U.S., Canada and Europe
        # PriceClass: "PriceClass_100"
        PriceClass: "PriceClass_All"
        # ... Alternate Domain Names (CNAMEs)
        # Aliases: 
        #  - !Sub ${DomainBaseURL}
        #  - !Sub "www.${DomainBaseURL}"
        # .............................
        Logging:
          Bucket: !Ref BucketLogsDNS
          Prefix: "cdn/"
          IncludeCookies: false
        # .............................
        DefaultCacheBehavior:
          # ---
          TargetOriginId: !Sub "${ProjectName}-${DomainBaseURL}-origin"
          # ---
          ViewerProtocolPolicy: "allow-all"
          #ViewerProtocolPolicy: "redirect-to-https"
          # ---
          AllowedMethods: 
            - "HEAD"
            - "GET"
          # ---
          CachedMethods: 
            - "HEAD"
            - "GET"
          # --- Managed cache policy and origin request policy
          # --- Managed-CachingOptimized
          CachePolicyId: "658327ea-f89d-4fab-a63d-7e88639e58f6"
          # ---
          Compress: false
          SmoothStreaming: false
        # .............................
        Origins: 
          - 
            Id: !Sub "${ProjectName}-${DomainBaseURL}-origin"
            # --- S3 Website Bucket IPv4 DNS
            DomainName: !Ref BucketRootDomainDNS
            # ---
            ConnectionAttempts: 3
            ConnectionTimeout: 10
            OriginPath: ""
            # ---
            S3OriginConfig:
              OriginAccessIdentity: !Sub "origin-access-identity/cloudfront/${CloudFrontOriginAccessIdentity}"


  # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  #         S3 BUCKET POLICY DEFINITION
  # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


  # ------------------------------------------
  # --- S3 Bucket Policy for Origin Identity Access
  BucketPolicyOriginAccessIdentity:
    Type: "AWS::S3::BucketPolicy"
    # .............................
    Properties:
      # .............................
      Bucket: !Sub "${DomainBaseURL}"
      PolicyDocument:
        Id: "PolicyForCloudFrontPrivateContent"
        Version: "2008-10-17"
        Statement:
          - Effect: "Allow"
            Action:
              - "s3:GetObject"
            Resource: !Sub "arn:aws:s3:::${DomainBaseURL}/*"
            Principal:
              CanonicalUser:
                !GetAtt CloudFrontOriginAccessIdentity.S3CanonicalUserId

# ==========================================
# Outputs: {}
Outputs:

  # ------------------------------------------
  # --- Website URL
  CloudfrontURL:
    Description: "The URL of Cloudfront Distribution."
    Value: !GetAtt CloudFrontDistribution.DomainName
